# CI de nivel 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
#gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

# tarefas dentro do pipeline = jobs

jobs:
  testes:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto para dentro da máquina do Actions
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      #instalação do Mocha
      - name: Instalando Mocha
        run: npm install -g mocha

      #instalação das dependencias
      - name: Instalando dependencias
        run: mocha

      # executar os testes
      - name: Executando testes
        run: npx run testes
